<?php

/**
 * ContactOpenIdConnectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactOpenIdConnectTable extends PluginContactOpenIdConnectTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactOpenIdConnectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContactOpenIdConnect');
    }
}