<?php

/**
 * GeoFrDistrictBaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeoFrDistrictBaseTable extends PluginGeoFrDistrictBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeoFrDistrictBaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeoFrDistrictBase');
    }
}