<?php

/**
 * YOB
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class YOB extends PluginYOB
{
  protected function getWithPadding($field, $pad = 2)
  {
    return $this->rawGet($field) ? str_pad($this->rawGet($field), $pad, '0', STR_PAD_LEFT) : '';
  }
  public function getDay()
  {
    return $this->getWithPadding('day');
  }
  public function getMonth()
  {
    return $this->getWithPadding('month');
  }
  public function getYear()
  {
    return $this->getWithPadding('year',4);
  }
  
  public function setFromString($yob)
  {
    $dob = DateTime::createFromFormat("Y-m-d\TH:i:sT", $yob);
    
    if ( $dob )
    {
      $this->year = $dob->format('Y');
      $this->month = $dob->format('m');
      $this->day = $dob->format('d');
    }
    
    return boolval($dob);
  }
  
  // ISO 8601
  public function toXFormat()
  {
    $str = '';
    $dob = DateTime::createFromFormat("Y-m-d H:i:s", $this->year.'-'.$this->month.'-'.$this->day.'00:00:00');
    
    if ( $dob )
    {
      $str = $dob->format('Y-m-d\TH:i:sT');
    }
    
    return $str;
  }
  
  public function __toString()
  {
    sfApplicationConfiguration::getActive()->loadHelpers(array('Date'));
    
    if ( $this->day && $this->month ) try {
      $r = format_date($this->year.'-'.$this->month.'-'.$this->day);
    } catch ( sfException $e ) { $r = (string)$this->year; }
    else
      $r = (string)$this->year;
    
    $r .= $this->name ? ' '.$this->name : '';
    
    return $r;
  }
}
