<?php

/**
 * PluginColorProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginColorProductCategoryTable extends ColorTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginColorProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginColorProductCategory');
    }
}