<?php

/**
 * PluginProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductTable extends TraceableTable implements CompositeSearchableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProduct');
    }
    
    public function batchUpdateIndex($limit = null, $offset = null, $encoding = null)
    {
      if ( !$this->hasTemplate('Searchable') )
        return false;
      return $this->getTemplate('Searchable')->getListener()->get('Searchable')->batchUpdateIndex($limit, $offset, $encoding);
    }
}