generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Contact
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          contact
    with_doctrine_route:   true
    actions_base_class:    sfActions
    extra:                 [show]

    config:
      actions: ~
      fields:
        event_archives: { label: Ticketting archives }
        description: { label: Keywords }
        YOBs_list:  { label: "Birthdays (x[, x [,..]])" }
        YOB:        { label: Birthdays }
        YOBs:       { label: Birthdays }
        not_groups_list: { label: Not member of groups }
        email_list: { label: Email }
        organisms_email_list: { label: Organism's email }
        family_contact: { label: Family contact }
        phone_type: { label: Type }
        phone_number: { label: Phonenumber }
        list_phones: { label: Phonenumbers }
        member_cards_valid_at: { label: Valid on }
        member_cards_not_valid_at: { label: Not valid on }
        control_created_at: { label: Passed in between }
        control_manifestation_id: { label: Passed on manifestations }
        control_checkpoint_id: { label: Controlled on checkpoints }
        tickets_amount_min: { label: Minimum tickets amount, help: Takes a long time }
        tickets_amount_max: { label: Maximum tickets amount, help: Takes a long time }
        list_emails: { label: Emails }
        list_see_orgs: { label: '', credentials: [pr-organism] }
        organisms_list: { label: Organisms, credentials: [pr-organism] }
        list_organism: { label: Organism }
        list_professional: { label: Professional, credentials: [pr-organism] }
        list_organism_phones_list: { label: Phonenumbers, credentials: [pr-organism] }
        list_professional_emails: { label: Emails }
        list_more: { label: More }
        list_nb: { label: Nb }
        list_contact: { label: Contact }
        list_organism_city: { label: City, credentials: [pr-organism] }
        list_organism_postalcode: { label: Postalcode, credentials: [pr-organism] }
        list_professional_description: { label: Description, credentials: [pr-organism] }
        list_professional_id: { label: '', credentials: [pr-organism] }
        list_professional_emails: { credentials: [pr-organism], label: Emails }
        familial_quotient_id: { credentials: [pr-social-quotient] }
        familial_situation_id: { credentials: [pr-social-situation] }
        type_of_resources_id: { credentials: [pr-social-resources] }
        email_no_newsletter: { label: No newsletter }
        email_newsletter: { label: Newsletter ? }
        email_npai:       { label: Bad email }
        organism_category_id: { credentials: [pr-organism] }
        organism_professional_id: { label: Close contact }
        groups_picto: { credentials: [pr-group], label: Remarkable }
        list_professional_groups_picto: { credentials: [pr-group], label: Remarkable }
        professional_groups_picto: { credentials: [pr-group], label: Remarkable }
        list_professional_groups_picto: { credentials: [pr-group], label: Remarkable }
        workspaces_list: { label: Workspaces }
        has_professional_type_id: { label: Any function? }
        survey_id:        { credentials: [TODO] }
        survey_query_id:  { credentials: [TODO], label: Query }
        survey_answer:    { credentials: [TODO], label: Answer }
        tickets_best_rank: { label: Best seat rank }
        tickets_avg_rank: { label: Average seat rank }
        tickets_rank_operand: { label: What kind of operand will we apply on seat ranks? }
        list_transactions: { label: Transactions }
        meta_events_list: { label: Meta events }
        manifestations_list: { label: Manifestations }
        member_cards_detail: { label: Promo code }
      list:
        display: [=name, _list_firstname, firstname, postalcode, city, _groups_picto, _list_emails, _list_phones, <?php if ( sfConfig::get('app_options_design',false) ): ?>_list_nb, _list_transactions, <?php endif ?>_organisms_list <?php if ( sfConfig::get('app_options_design',false) ): ?>, description, _list_see_orgs, _list_contact, _list_professional_id, _list_organism, _list_professional, _list_organism_postalcode, _list_organism_city, _list_professional_emails, _list_organism_phones_list, _list_professional_groups_picto, _list_professional_description<?php endif ?>]
        max_per_page: <?php if ( sfConfig::get('app_options_design',false) ): ?>50<?php else: ?>20<?php endif; echo PHP_EOL; ?>
        table_method: retreiveList
        object_actions:
          <?php if ( sfConfig::get('app_options_design',false) != 'tdp' ): echo PHP_EOL; ?>
          _show: ~
          <?php else: echo PHP_EOL; ?>
          _showUp:
            label: Show up
            action: edit
          <?php endif; echo PHP_EOL; ?>
          _edit: ~
          _delete: ~
        sort: ['c.name, c.firstname', '']
      filter:
        display:
          Personal: [title, name, firstname, shortname, postalcode, city, region_id, country, email]
          <?php if ( sfConfig::get('app_contact_social_informations', false) ): echo PHP_EOL; ?>
          Social informations: [familial_quotient_id, familial_situation_id, type_of_resources_id]
          <?php endif ?><?php echo PHP_EOL ?>
          Relations: [groups_intersection, not_groups_list, groups_list, organism_id, organism_category_id, professional_type_id, has_professional_type_id, organism_professional_id]
          <?php if ( sfConfig::get('app_cards_enable',false) ): ?><?php echo PHP_EOL ?>
          Member cards: [member_cards, member_cards_detail, member_cards_valid_at, member_cards_not_valid_at, member_cards_only_last]
          <?php endif ?><?php echo PHP_EOL ?>
          Events: [event_categories_list, meta_events_list, events_list, manifestations_list, workspaces_list, prices_list, <?php if ( sfConfig::get('app_no_event_archives',true) ): ?>event_archives,<?php endif ?> tickets_amount_min, tickets_amount_max, tickets_best_rank, tickets_avg_rank, tickets_rank_operand]
          <?php if ( sfConfig::get('app_controls_enabled',false) ): ?><?php echo PHP_EOL ?>
          Flow management: [control_created_at, control_manifestation_id, control_checkpoint_id]
          <?php endif ?><?php echo PHP_EOL ?>
          Surveys: [survey_id, survey_query_id, survey_answer]
          Additional: [culture, description, YOB, email_npai, email_newsletter, family_contact, npai, has_address, has_email, has_category, emails_list, updated_at]
      form: ~
      edit:
        title: Contact %%name%% %%firstname%%
        display:
          NONE:  [title, name, firstname, shortname, address, postalcode, _cities, city, country, email, <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>email_no_newsletter,<?php endif ?> _show_member_cards_list, groups_list]
          Phonenumbers: [_form_phonenumbers_list]
          Precisions: [family_contact, npai, description, YOBs, password]
          Ticketting: [_show_events_list]
          Social: [_familial_situation_id, _type_of_resources_id, _familial_quotient_id, Relationships]
      new:
        title: New contact
        display:
          NONE:  [title, name, firstname, address, postalcode, _cities, city, country, email, <?php if ( sfConfig::get('app_options_design',false) && sfConfig::get(sfConfig::get('app_options_design').'_active') ): ?>email_no_newsletter,<?php endif ?>groups_list]
          Phonenumber: [phone_type, phone_number]
          Precisions: [family_contact, npai, description, YOBs, password]
          Social: [familial_situation_id, type_of_resources_id, familial_quotient_id, Relationships]
      show: 
        display:
          NONE: [_show_who, address, postalcode, city, country, _show_region, _show_email, _show_phonenumbers_list, _show_member_cards_list, _show_groups_list]
          Precisions: [_show_family_contact, npai, description, _YOBs]
          Technic: [created_at,updated_at,slug,longitude,latitude]
          Ticketting: [_show_events_list]
          Social: [_familial_situation_id, _type_of_resources_id, _familial_quotient_id, _show_relationships_list, _show_foreign_relationships_list]
