<?php

/**
 * PluginGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGroup');
    }
    
    // Optimization for domain restrictions
    public function getRelation($alias, $recursive = true)
    {
      $rel = parent::getRelation($alias, $recursive);
      try { $rel = liDoctrineRelationAssociationUsers::create($rel); }
      catch ( liEvenementException $e ) { }
      return $rel;
    }
}
