<?php

/**
 * DummyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DummyTable extends PluginDummyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DummyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dummy');
    }
}