<?php

/**
 * PluginCustomCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCustomCardTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCustomCardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCustomCard');
    }
}