<?php

/**
 * PluginMemberCard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginMemberCard extends BaseMemberCard
{
  public function preSave($event)
  {
    if ( !$this->transaction_id && $this->Payments->count() > 0 )
      $this->Transaction = $this->Payments[0]->Transaction;
    
    if ( $this->MemberCardType->product_declination_id
      && $this->MemberCardType->price_id
      && $this->Transaction->MemberCards->count() > 0
      && $this->BoughtProducts->count() == 0
    )
    {
      $bp = new BoughtProduct;
      $bp->Declination = $this->MemberCardType->ProductDeclination;
      $bp->Price = $this->MemberCardType->Price;
      $bp->Transaction = $this->Transaction;
      $bp->Transaction->contact_id = $this->contact_id;
      $bp->integrated_at = date('Y-m-d H:i:s');
      $this->BoughtProducts[] = $bp;
    }
    
    if ( !$this->expire_at )
    {
      $this->expire_at = sfConfig::has('project_cards_expiration_delay')
        ? date('Y-m-d H:i:s',strtotime(sfConfig::get('project_cards_expiration_delay')))
        : (strtotime(date('Y').'-'.sfConfig::get('project_cards_expiration_date')) > strtotime('now')
          ? date('Y').'-'.sfConfig::get('project_cards_expiration_date')
          : (date('Y')+1).'-'.sfConfig::get('project_cards_expiration_date')
        );
    }
    
    parent::preSave($event);
  }
  
  public function postSave($event)
  {
    $this->processInfinitePrices();
    parent::postSave($event);
  }
  public function postInsert($event)
  {
    // prices
    $q = Doctrine::getTable('MemberCardPriceModel')->createQuery('pm')
      ->andWhere('pm.member_card_type_id = ?',$this->member_card_type_id)
      ->andWhere('pm.quantity > 0');
    $models = $q->execute();
    
    foreach ( $models as $model )
    for ( $i = 0 ; $i < $model->quantity ; $i++ )
    {
      $mc_price = new MemberCardPrice;
      $mc_price->price_id = $model->price_id;
      $mc_price->event_id = $model->event_id;
      $mc_price->member_card_id = $this->id;
      $mc_price->save();
    }
    
    parent::postInsert($event);
  }
  
  protected function processInfinitePrices()
  {
    // prices
    $q = Doctrine::getTable('MemberCardPriceModel')->createQuery('pm')
      ->andWhere('pm.member_card_type_id = ?',$this->member_card_type_id)
      ->andWhere('pm.quantity < 0');
    
    foreach ( $q->execute() as $model )
    {
      // do not add existing prices
      foreach ( $this->MemberCardPrices as $mcp )
      if ( $mcp->price_id == $model->price_id )
        $model->quantity++;
      
      for ( $i = 0 ; $i < -$model->quantity ; $i++ )
      {
        $mc_price = new MemberCardPrice;
        $mc_price->price_id = $model->price_id;
        $mc_price->event_id = $model->event_id;
        $mc_price->member_card_id = $this->id;
        $mc_price->save();
        $this->MemberCardPrices[] = $mc_price;
      }
    }
  }
  
  public function getIndexesPrefix()
  {
    return strtolower(get_class($this));
  }
}
