<?php

/**
 * PluginCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCountry');
    }
}