<?php

/**
 * PluginColorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginColorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginColorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginColor');
    }
    
    public function createQuery($alias = 'col') 
    {
      $q = parent::createQuery($alias);
      
      if ( ($dom = sfConfig::get('project_internals_users_domain', false)) && $dom != '.' )
        $q->andWhere("$alias.domain = ? OR $alias.domain LIKE ?", array('%.'.$dom, $dom));
        
      return $q;
    }
    
}