<?php

/**
 * PluginDummyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDummyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDummyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDummy');
    }
}