<?php

/**
 * ColorPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColorPriceTable extends PluginColorPriceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColorPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ColorPrice');
    }
}