<?php

/**
 * ProductPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductPriceTable extends PluginProductPriceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductPrice');
    }
    
    public function createQuery($alias = 'p', $override_credentials = true, $target = 'pos')
    {
      $q = parent::createQuery($alias, $override_credentials, $target);

      return $q;
    }
    
}