<?php

/**
 * PluginEntryElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEntryElement extends BaseEntryElement
{
  public function preSave($con)
  {
    if ( Doctrine::getTable('EntryElement')->createQuery('ee')
      ->andWhere('ee.manifestation_entry_id = ?', $this->manifestation_entry_id)
      ->andWhere('ee.contact_entry_id = ?', $this->contact_entry_id)
      ->count() > 0 )
      return;
    parent::preSave($con);
  }
}
