<?php

/**
 * ColorManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColorManifestationTable extends PluginColorManifestationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColorManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ColorManifestation');
    }
}