<?php

/**
 * EventPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventPictureTable extends PluginEventPictureTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventPicture');
    }
}