<?php

/**
 * OsApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OsApplicationTable extends PluginOsApplicationTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OsApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OsApplication');
    }
}