<?php

/**
 * OsTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OsTokenTable extends PluginOsTokenTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OsTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OsToken');
    }
}