<?php

/**
 * OptionGaugeTimeoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OptionGaugeTimeoutTable extends PluginOptionGaugeTimeoutTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OptionGaugeTimeoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OptionGaugeTimeout');
    }
}