<?php

/**
 * ColorProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColorProductCategoryTable extends PluginColorProductCategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColorProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ColorProductCategory');
    }
}