<?php

/**
 * ProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryTable extends PluginProductCategoryTable
{
  public function createQuery($alias = 'pc')
  {
    $q = parent::createQuery($alias)
      ->leftJoin("$alias.Translation pct")
      ->leftJoin("$alias.Parent ppc")
      ->select('*')
      ->addSelect('(CASE WHEN ppc.id IS NULL THEN pct.name ELSE (SELECT ppct.name FROM ProductCategoryTranslation ppct WHERE ppct.lang = pct.lang AND ppct.id = ppc.id) END) AS parent_name')
    ;
    
    return $this->addDomainRestriction($q, $alias);
  }
  
  public function addDomainRestriction($q, $alias) 
  {
    return $q->andWhere("$alias.domain = ? OR $alias.domain = ?", sfConfig::get('project_internals_users_domain', '') && sfConfig::get('project_internals_users_domain', '') != '.'
      ? array(
          $domain = preg_replace('/\.$/', '', sfConfig::get('project_internals_users_domain', '')),
          $domain.'.',
        )
      : array('', '.')
    );
  }
  
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ProductCategory');
  }
  
  public function retrievePublicList()
  {
    $q = $this->createQuery('pc')
      ->leftJoin('pc.Products p')
      ->leftJoin('p.Translation pt')
      ->leftJoin('p.Declinations d')
      ->leftJoin('d.Translation dt')
      ->leftJoin('pc.Children children')
      ->leftJoin('children.Translation childrent')
    ;
    
    $user = sfContext::hasInstance() ? sfContext::getInstance()->getUser() : NULL;
    if ( $user )
      $q->andWhereIn('p.meta_event_id IS NULL OR p.meta_event_id', array_keys($user->getMetaEventsCredentials()));
    
    $q->andWhere('pc.online = ?', true)
      ->leftJoin('p.Prices price')
      ->leftJoin('price.Users u WITH u.id = '.$user->getId()) // cannot use '?' to avoid bugs
      ->andWhere('u.id IS NOT NULL OR children.id IS NOT NULL')
    ;
    if ( $user )
      $q->andWhere('u.id = ? OR children.id IS NOT NULL', $user->getId());
    
    if ( isset($_GET['cid']) && $_GET['cid'] && intval($_GET['cid']).'' === ''.$_GET['cid'] )
      $q->andWhere('pc.product_category_id = ? OR pc.id = ?', array($_GET['cid'], $_GET['cid']));
    else
      $q->andWhere('pc.product_category_id IS NULL');
    
    return $q;
  }
}
