<?php

/**
 * ProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductCategory extends PluginProductCategory
{
  public function getStructuredShippingFees()
  {
    if ( !$this->shipping_fees )
      return false;
    
    return json_decode($this->shipping_fees, true);
  }
  
  public function getShippingFeesFor($weight)
  {
    if (!( $struct = $this->getStructuredShippingFees() ))
      return false;
    
    foreach ( $struct as $range )
    if ( $range['min'] !== null && $weight >= $range['min']
      && $range['max'] !== null && $weight <  $range['max'] )
      break;
    
    return $range['fees'];
  }
}
