<?php

/**
 * nvSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class nvSessionTable extends PluginnvSessionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object nvSessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('nvSession');
    }
}