generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MemberCardType
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          member_card_type
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        value: { help: Global price, type: number }
        real_value: { type: number }
        nb_tickets_mini: { label: Minimum quantity of tickets needed in online sales, type: number }
        product_declination_id: { label: Product, help: This product will become the inner price of those member cards }
        price_id: { help: 'This price will be applied, as it is defined inside the product...' }
      list:
        display: [name, description, _value, _real_value, nb_tickets_mini]
        fields:
          nb_tickets_mini: { label: Tickets online }
        sort: [name, asc]
        object_actions:
          _edit: ~
          _delete: ~
      filter:  ~
      form:
        display:
          NONE: [name, description, users_list, nb_tickets_mini, _show_url_public]
          Money: [value, product_declination_id, price_id]
          Online: [public_details]
          Promo Codes: [promo_codes, _form_promo_codes, _form_promo_code_del]
      edit:
        actions:
          _list: ~
          _delete: ~
          _promo_code:
            action: addPromoCode
            ui-icon: plus
            label: Promo Code
            credentials: pr-card-promo-new
          _save: ~
      new:     ~
