<?php

/**
 * PluginOptionKioskTextsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionKioskTextsTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionKioskTextsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionKioskTexts');
    }
}