<?php

/**
 * PluginAdminTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAdminTaskTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAdminTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAdminTask');
    }
}