<?php

/**
 * PluginEptRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEptRecordTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEptRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEptRecord');
    }
}