<?php

/**
 * OptionTckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OptionTckTable extends PluginOptionTckTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OptionTckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OptionTck');
    }
}