<?php

/**
 * PluginColorManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginColorManifestationTable extends ColorTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginColorManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginColorManifestation');
    }
}