<?php

/**
 * PluginGauge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginGauge extends BaseGauge
{
  /**
   * getPriceGaugesFiltered()
   * filtering the PriceGauges returned depending on the availability of their Price in the current Workspace
   *
   * @return Doctrine_Collection of PriceGauge
   **/
  public function getPriceGaugesFiltered()
  {
    $pgs = new Doctrine_Collection('PriceGauge');
    
    foreach ( $this->PriceGauges as $pg )
    if ( in_array($pg->price_id, $this->Workspace->Prices->getPrimaryKeys()) )
      $pgs[] = $pg;
    
    return $pgs;
  }
  
  /**
   * getPriceManifestationsFiltered()
   * filtering the PriceManifestations returned depending on the availability of their Price in the current Workspace
   *
   * @return Doctrine_Collection of PriceManifestation
   **/
  public function getPriceManifestationsFiltered()
  {
    $pms = new Doctrine_Collection('PriceManifestation');
    
    foreach ( $this->Manifestation->PriceManifestations as $pm )
    if ( in_array($pm->price_id, $this->Workspace->Prices->getPrimaryKeys()) )
      $pms[] = $pm;
    
    return $pms;
  }
}
