<?php

/**
 * PluginHoldTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHoldTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHoldTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHold');
    }
    
    public function createQuery($alias = 'e')
    {
      $q = parent::createQuery($alias);
      
      if ( !sfContext::hasInstance() || !sfContext::getInstance()->getActionName() )
        $q->leftJoin("$alias.Translation ht");
      elseif (!( sfContext::hasInstance()
        && sfContext::getInstance()->getActionName()
        && in_array(sfContext::getInstance()->getActionName(), array('edit', 'update'))
      ))
      {
        $culture = sfContext::hasInstance() ? sfContext::getInstance()->getUser()->getCulture() : 'fr';
        $q->leftJoin("$alias.Translation ht WITH ht.lang = '$culture'");
      }
      else
        $q->leftJoin("$alias.Translation ht");
      
      return $q;
    }
}