<?php

/**
 * PluginManifestationPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginManifestationPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginManifestationPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginManifestationPicture');
    }
}