<?php

/**
 * PluginWorkspaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkspaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkspaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkspace');
    }
  // Optimization for domain restrictions
  public function getRelation($alias, $recursive = true)
  {
    $rel = parent::getRelation($alias, $recursive);
    try { $rel = liDoctrineRelationAssociationUsers::create($rel); }
    catch ( liEvenementException $e ) { }
    return $rel;
  }
}
