<?php

/**
 * PluginSeatedPlanZoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSeatedPlanZoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSeatedPlanZoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSeatedPlanZone');
    }
}