<?php

/**
 * PluginMetaEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginMetaEvent extends BaseMetaEvent implements liDuplicable
{
  public function getUsers($load)
  {
    return liDoctrineRelationAssociationUsers::removeUpperUsersFromCollection($this->_get('Users', $load));
  }

  public function duplicate()
  {
  	sfApplicationConfiguration::getActive()->loadHelpers('I18N');
  	$new = $this->copy();

  	foreach( $this->Events as $event )
      $new->Events[] = $event->duplicate();
    foreach( $this->Users as $user )
      $new->Users[] = $user;

  	$new->slug = NULL;
  	$new->name = sprintf('%s  (%s)', $this->name, __('copy'));

  	$new->save();

  	return $new;
  }
}
