<?php

/**
 * PluginLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginLocation extends BaseLocation
{
  public function preInsert($event)
  {
    // the current domain is a default value for the domain field
    if ( !$this->domain )
      $this->domain = sfConfig::get('project_internals_users_domain', '.');
    
    parent::preInsert($event);
  }
  
  public function preSave($event)
  {
    // do not update the domain field...
    $mods = $this->getModified(true);
    if ( $mods['domain'] )
      $this->domain = $mods['domain'];
    
    parent::preSave($event);
  }
  
  public function getIndexesPrefix()
  {
    return strtolower(get_class($this));
  }
}
