<?php

/**
 * PluginEventPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEventPicture');
    }
}