<?php

/**
 * PluginProductPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductPriceTable extends PriceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProductPrice');
    }
}