<?php

/**
 * PluginPriceRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPriceRankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPriceRankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPriceRank');
    }
    
    public function createQuery($alias = 'pr')
    {
      $q = parent::createQuery($alias);
      
      if ( $dom = sfConfig::get('project_internals_users_domain', null) )
        $q->andWhere("$alias.domain = ?", $dom);    // Root domain should not access sub domains
        
      return $q;
    }
}