<?php

/**
 * PluginProductPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginProductPrice extends BaseProductPrice
{
  public function preSave($event)
  {
    $this->target = 'pos';
    parent::preSave($event);
  }
  
  public function postSave($event) 
  {
    parent::preSave($event);
    
    $this->PricePOS->price_id = $this->id;
  }
}
