<?php

/**
 * PluginPriceRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPriceRankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPriceRankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPriceRank');
    }
}