<?php

/**
 * PluginOptionTckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionTckTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionTckTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionTck');
    }
}