<?php

/**
 * CustomCardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomCardTable extends PluginCustomCardTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomCardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomCard');
    }
}