<?php

/**
 * PluginDirectPrintTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDirectPrintTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDirectPrintTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDirectPrint');
    }
}