<?php

/**
 * PluginPaymentMethod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPaymentMethod extends BasePaymentMethod
{
  public function postInsert($event)
  {
    $rank = new PaymentMethodRank;
    $rank->rank = $this->id;
    $rank->payment_method_id = $this->id;
    $rank->domain = sfConfig::get('project_internals_users_domain', '');
    $rank->save();      
    
    $this->Ranks[0] = $rank;
  
    return parent::postInsert($event);
  }
}
