<?php

/**
 * PluginPaymentMethodUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPaymentMethodUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPaymentMethodUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPaymentMethodUser');
    }
}