<?php

/**
 * PluginPaymentMethodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPaymentMethodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPaymentMethodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPaymentMethod');
    }
    
    public function createQuery($alias = 'pm')
    {
      $q = parent::createQuery($alias);
      
      if ( $dom = sfConfig::get('project_internals_users_domain', null) )
        $q->leftJoin("$alias.Ranks pmr WITH pmr.domain ILIKE ? OR pmr.domain = ?", array('%.'.$dom, $dom));
      else
        $q->leftJoin("$alias.Ranks pmr");
        
      $q->orderBy("pmr.rank, $alias.id");      

     return $q;
    }
}