<?php

/**
 * PluginOptionGaugeTimeoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionGaugeTimeoutTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionGaugeTimeoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionGaugeTimeout');
    }
}