<?php

/**
 * DirectPrintTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DirectPrintTable extends PluginDirectPrintTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DirectPrintTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DirectPrint');
    }
}