<?php

/**
 * OrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderTable extends PluginOrderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Order');
    }
    
    public function fetchOneById($id)
    {
      return $this->createQuery('a')->andWhere('id = ?',$id)->fetchOne();
    }
    public function doSelectIndex(Doctrine_Query $q)
    {
      $o = $q->getRootAlias();
      $q->leftJoin("$o.User u")
        ->leftJoin("$o.Transaction t")
        
        ->leftJoin('t.Tickets tck')
        ->leftJoin('tck.Manifestation m')
        ->leftJoin('m.Location l')
        ->leftJoin('m.Event e')
        ->leftJoin('tck.Gauge g')
        ->leftJoin('m.Workspaces w')
        ->leftJoin('e.MetaEvent me')
        ->leftJoin('e.EventCategory ec')
        ->leftJoin('t.Contact c')
        ->leftJoin('t.Professional p')
        ->leftJoin('p.Organism org')
      ;
      
      if ( ($dom = sfConfig::get('project_internals_users_domain', false)) && $dom != '.' )
        $q->leftJoin("t.User tu ON tu.id = (SELECT tv.sf_guard_user_id FROM TransactionVersion tv WHERE tv.id = t.id AND tv.version = 1)")
          ->leftJoin('tu.Domain d')
          ->andWhere('d.name ILIKE ? OR d.name = ?', array('%.'.$dom, $dom));
            
      
      return $q;
    }
}
