<?php

/**
 * PaymentMethodRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentMethodRankTable extends PluginPaymentMethodRankTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentMethodRankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaymentMethodRank');
    }
}