<?php

/**
 * PaymentMethodUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentMethodUserTable extends PluginPaymentMethodUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentMethodUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaymentMethodUser');
    }
}