<?php

/**
 * PaymentMethod
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    e-venement
 * @subpackage model
 * @author     Baptiste SIMON <baptiste.simon AT e-glop.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PaymentMethod extends PluginPaymentMethod
{
  /**
   * Returns the PaymentMethod name prefixed with _EPT_ when $this->ept is true
   * @return string
   */
  public function toStringEPT()
  {
    return $this->ept ? '_EPT_'.$this->name : $this->name;
  }
}
