<?php

/**
 * TicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketTable extends PluginTicketTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ticket');
    }
  
  public function createQuery($alias = 'tck')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Duplicatas duplicatas");
  }
  
  public function createQueryRealTickets($alias = 'tck')
  {
    return parent::createQuery($alias)
      ->andWhere("$alias.duplicating IS NULL AND $alias.id NOT IN (SELECT tck1.duplicating FROM ticket tck1 WHERE tck1.duplicating IS NOT NULL)")
      ->andWhere("$alias.cancelling IS NULL AND $alias.id NOT IN (SELECT tck2.cancelling FROM ticket tck2 WHERE tck2.cancelling IS NOT NULL)")
    ;
  }
  
  public function createQueryPreparedForRanks($alias = 'tck')
  {
    return parent::createQuery($alias)
      ->leftJoin("$alias.Seat {$alias}_s")
      ->andWhere("$alias.printed_at IS NOT NULL OR $alias.integrated_at IS NOT NULL")
      ->andWhere("$alias.seat_id IS NOT NULL")
      
      ->leftJoin("$alias.Transaction {$alias}_t")
      
      //->having("{$sql_fct}({$alias}_s.rank) $operand $value")
      //->groupBy("{$alias}_t.contact_id')
    ;
  }
  
  public function getOneFromMembercard($card_id, $manifestation_id)
  {
    return Doctrine_Query::create()
      ->select('tck.*')
      ->from('Ticket tck')
      ->innerJoin('tck.Manifestation m')
      ->innerJoin('m.Event e')
      ->innerJoin('e.Checkpoints cp WITH cp.type = ?', 'entrance')
      ->leftJoin('tck.Controls c WITH c.checkpoint_id = cp.id')
      ->where('c.id IS NULL')
      ->andWhere('(tck.printed_at IS NOT NULL OR tck.integrated_at IS NOT NULL)')
      ->andWhere('tck.manifestation_id = ?', $manifestation_id)
      ->andWhere('tck.member_card_id = ?', $card_id)
      ->orderBy('tck.created_at')
      ->fetchOne();
  }
  
  public function getOneFromCode($ticket_code, $check_type)
  {
    return Doctrine::getTable('Ticket')->createQuery('tck')
      ->innerJoin('tck.Manifestation m')
      ->innerJoin('m.Event e')
      ->innerJoin('e.Translation et')
      ->leftJoin('e.Checkpoints cp WITH cp.type = ?', $check_type)
      ->leftJoin('tck.Controls c WITH c.checkpoint_id = cp.id')
      ->andWhere('tck.barcode = ?', $ticket_code)
      ->fetchOne();
  }
  
  public function getLastControlled($manifestation_id)
  {
    return Doctrine::getTable('Ticket')->createQuery('tck')
      ->innerJoin('tck.Controls c')
      ->innerJoin('c.Checkpoint cp WITH cp.type = ?', 'entrance')
      ->leftJoin('tck.Controls ce WITH ce.id != c.id')
      ->leftJoin('ce.Checkpoint cpe WITH cpe.type = ?', 'exit')
      ->where('tck.manifestation_id = ?', $manifestation_id)
      ->andWhere('ce.id IS NULL')
      ->orderBy('c.created_at')
      ->fetchOne();
  }
}
