<?php

/**
 * AdminTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminTaskTable extends PluginAdminTaskTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminTask');
    }
}