<?php

/**
 * EptRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EptRecordTable extends PluginEptRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EptRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EptRecord');
    }
}