<?php

/**
 * PluginGeoFrStreetBaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginGeoFrStreetBaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginGeoFrStreetBaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginGeoFrStreetBase');
    }
}