<?php

/**
 * PluginOptionPubTextsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOptionPubTextsTable extends OptionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOptionPubTextsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOptionPubTexts');
    }
}