<?php

/**
 * PluginContactOpenIdConnectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactOpenIdConnectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactOpenIdConnectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContactOpenIdConnect');
    }
}